steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/ipfs-counter:$SHORT_SHA'
  - '-t'
  - 'gcr.io/$PROJECT_ID/ipfs-counter:latest'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/ipfs-counter:latest'
